apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  capacity:
    storage: 1Gi # The size of the volume
  volumeMode: Filesystem # The type of volume
  storageClassName: standard # The storage class of the volume
  accessModes:
    - ReadWriteOnce # The access mode of the volume, which means it can be mounted as read-write by a single node, multiple pods with in the same node can claim it.
  hostPath:
    path: /data # this is the path on the host machine where the volume will be mounted
    type: DirectoryOrCreate # this will create the directory if it doesn't exist
