apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-pvc
spec:
  volumeName: host-pv # The name of the persistent volume to bind to
  accessModes:
    - ReadWriteOnce # The access mode of the volume, which means it can be mounted as read-write by a single node, multiple pods with in the same node can claim it.
  storageClassName: standard # The storage class of the volume
  resources:
    requests:
      storage: 1Gi # The size of the volume the maximum size of the volume allowed to be claimed you could claim less to allow other nodes to claim the remaining space.

