FROM node:14-alpine

WORKDIR /app

ENTRYPOINT [ "npm" ]

# docker build -t node-util .

# docker run -it -v $(pwd):/app --name node-util-container node-util npm init
# - without entrypoint


# docker run -it -v $(pwd):/app --name node-util-container node-util init
# docker run -it --rm -v $(pwd):/app --name node-util-container node-util install
# docker run -it --rm -v $(pwd):/app --name node-util-container node-util install express --save