FROM node:14-alpine as build

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

RUN npm run build

FROM nginx:stable-alpine

COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]



# docker build -f frontend/Dockerfile.prod -t academind/goals-react ./frontend

# docker build --target build -f frontend/Dockerfile.prod -t academind/goals-react ./frontend
# if only I want to stop at the build stage