version: "3"
services:
  auth:
    build: ./auth-api
  users:
    build: ./users-api
    ports:
      - "8080:8080"
    environment:
      # AUTH_SERVICE_SERVICE_HOST: auth
      AUTH_ADDRESS: auth
  tasks:
    build: ./tasks-api
    ports:
      - "8000:8000"
    environment:
      AUTH_ADDRESS: auth
      TASKS_FOLDER: tasks
