FROM python

WORKDIR /app

COPY . .

CMD ["python", "rng.py"]

# docker build . "-to build the image"
# docker run -it <image_id> "-to run a container from the image in (i) interactive mode and (t) create a terminal"
# docker start -a -i <container_id> "-to start a stopped container and attach to it"