apiVersion: v1
kind: Service
metadata:
  name: tasks-service # can be accessed within the cluster using env `TASKS_SERVICE_SERVICE_HOST`
spec:
  selector:
    app: tasks
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
