apiVersion: v1
kind: Service
metadata:
  name: users-service # can be accessed within the cluster using env `USERS_SERVICE_SERVICE_HOST`
spec:
  selector:
    app: users
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
